/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface;

import java.awt.Container;
import javax.swing.JComponent;
import javax.swing.JScrollPane;
import javax.swing.JViewport;
import org.Atletismo;
import org.Basquetebol;
import org.Caminhada;
import org.FitnessUM;
import org.Futebol;
import org.Natacao;
import org.Voleibol;

/**
 *
 * @author teste
 */
public class AddActividade extends javax.swing.JFrame {

    FitnessUM fitnessUM;
    
    public static final JScrollPane getScrollPane( JComponent component ) {

         Container p = component .getParent();
         if (p instanceof JViewport) {
                Container gp = p.getParent();
                if (gp instanceof JScrollPane) {
                    return (JScrollPane)gp;
                }
         }
         return null;

    }
    
    /**
     * Creates new form AddActividade
     */
    public AddActividade(FitnessUM fitnessUM) {
        initComponents();
        this.fitnessUM = fitnessUM;
        jComboBox2.addItem("Natação");
        jComboBox2.addItem("Caminhada");
        jComboBox2.addItem("Futebol");
        jComboBox2.addItem("Basquetebol");
        jComboBox2.addItem("Voleibol");
        jComboBox2.addItem("Ciclismo");
        jComboBox2.addItem("Atletismo");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane7 = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane8 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextPane10 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("FitnessUM");

        jLabel2.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel2.setText("Tipo:");

        jComboBox2.setName("cb_desporto"); // NOI18N
        jComboBox2.setPreferredSize(new java.awt.Dimension(127, 23));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel3.setText("Condições Meteorológicas");

        jLabel4.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel4.setText("Local");

        jScrollPane1.setViewportView(jTextPane1);

        jScrollPane2.setViewportView(jTextPane2);

        jLabel5.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel5.setText("Data");

        jScrollPane3.setViewportView(jTextPane3);

        jLabel6.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel6.setText("Distancia percorrida (km)");

        jScrollPane4.setViewportView(jTextPane4);

        jScrollPane5.setViewportView(jTextPane5);

        jLabel7.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel7.setText("Pontos");

        jLabel8.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel8.setText("Golos");

        jScrollPane6.setViewportView(jTextPane6);

        jLabel9.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel9.setText("Cestos");

        jScrollPane7.setViewportView(jTextPane7);

        jLabel10.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel10.setText("Altitude(km)");

        jScrollPane8.setViewportView(jTextPane8);

        jButton1.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel12.setText("Duração (min)");

        jScrollPane10.setViewportView(jTextPane10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)))
                        .addGap(340, 340, 340))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel7)
                                        .addComponent(jScrollPane3)
                                        .addComponent(jLabel8)
                                        .addComponent(jScrollPane6)
                                        .addComponent(jLabel9)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)))
                                .addGap(165, 165, 165))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(22, 22, 22))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel8))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        switch((jComboBox2.getSelectedItem().toString()))
        {
            case "Natação" :
                
                jLabel6.setVisible(true);
                jTextPane4.setVisible(true);
                jLabel7.setVisible(false);
                jLabel8.setVisible(false);
                jLabel10.setVisible(false);
                jLabel9.setVisible(false);
                jTextPane3.setVisible(false);
                getScrollPane(jTextPane3).setVisible(false);
                jTextPane3.setVisible(false);
                jTextPane6.setVisible(false);
                getScrollPane(jTextPane6).setVisible(false);
                jTextPane7.setVisible(false);
                getScrollPane(jTextPane7).setVisible(false);
                jTextPane8.setVisible(false);
                getScrollPane(jTextPane8).setVisible(false);
                
                
            case "Caminhada" :
            
                jLabel6.setVisible(true);
                jLabel7.setVisible(false);
                jLabel8.setVisible(false);
                jLabel9.setVisible(false);
                jLabel10.setVisible(true);
                jTextPane4.setVisible(true);
                jTextPane3.setVisible(false);
                getScrollPane(jTextPane3).setVisible(false);
                jTextPane6.setVisible(false);
                getScrollPane(jTextPane6).setVisible(false);
                jTextPane7.setVisible(false);
                getScrollPane(jTextPane7).setVisible(false);
                jTextPane8.setVisible(true);
            
            
            case "Atletismo" :
            
                jLabel6.setVisible(true);
                jLabel7.setVisible(false);
                jLabel8.setVisible(false);
                jLabel9.setVisible(false);
                jLabel10.setVisible(true);
                jLabel10.setVisible(false);
                jTextPane3.setVisible(false);
                getScrollPane(jTextPane3).setVisible(false);
                jTextPane4.setVisible(true);
                jTextPane6.setVisible(false);
                getScrollPane(jTextPane6).setVisible(false);
                jTextPane7.setVisible(false);
                getScrollPane(jTextPane7).setVisible(false);
                jTextPane8.setVisible(true);
             
            
            case "Futebol" :
            
               jLabel6.setVisible(true);
               jLabel7.setVisible(false);
               jLabel8.setVisible(true);
               jLabel9.setVisible(false);
               jLabel10.setVisible(false); 
               jTextPane4.setVisible(true);
               jTextPane3.setVisible(false);
               getScrollPane(jTextPane3).setVisible(false);
               jTextPane6.setVisible(true);
               jTextPane7.setVisible(false);
               getScrollPane(jTextPane7).setVisible(false);
               jTextPane8.setVisible(false);
               getScrollPane(jTextPane8).setVisible(false);
            
            case "Ciclismo":
            
                jLabel6.setVisible(true);
                jLabel7.setVisible(false);
                jLabel8.setVisible(false);
                jLabel9.setVisible(false);
                jLabel10.setVisible(true);
                jTextPane4.setVisible(true);
                jTextPane3.setVisible(false);
                getScrollPane(jTextPane3).setVisible(false);
                jTextPane6.setVisible(false);
                getScrollPane(jTextPane6).setVisible(false);
                jTextPane7.setVisible(false);
                getScrollPane(jTextPane7).setVisible(false);
                jTextPane8.setVisible(true);
                
            
            case "Voleibol":
            
                jLabel6.setVisible(false);
                jLabel7.setVisible(true);
                jLabel8.setVisible(false);
                jLabel9.setVisible(false);
                jLabel10.setVisible(false);
                jTextPane4.setVisible(false);
                getScrollPane(jTextPane4).setVisible(false);
                jTextPane3.setVisible(true);
                jTextPane6.setVisible(false);
                getScrollPane(jTextPane6).setVisible(false);
                jTextPane7.setVisible(false);
                getScrollPane(jTextPane7).setVisible(false);
                jTextPane8.setVisible(false);
                getScrollPane(jTextPane8).setVisible(false);

            
            case "Basquetebol":
            
                jLabel6.setVisible(true);
                jLabel7.setVisible(false);
                jLabel8.setVisible(false);
                jLabel9.setVisible(true);
                jLabel10.setVisible(false);
                jTextPane3.setVisible(false);
                getScrollPane(jTextPane3).setVisible(false);
                jTextPane6.setVisible(false);
                getScrollPane(jTextPane6).setVisible(false);
                jTextPane4.setVisible(false);
                jTextPane8.setVisible(false);
                getScrollPane(jTextPane8).setVisible(false);
                jTextPane7.setVisible(true);

                   
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        switch((jComboBox2.getSelectedItem().toString()))
        {
            case "Natação" :
            Natacao natacao = new Natacao();
            
            natacao.setDuracao((long)(Integer.parseInt(jTextPane10.getText())));
            natacao.setDistancia((double)(Integer.parseInt(jTextPane4.getText())));
            natacao.setCondMeteo(jTextPane1.getText());
            natacao.setLocal(jTextPane5.getText());
            natacao.setData(jTextPane2.getText());
            
            this.fitnessUM.adicionaActividade(natacao);
                
            case "Caminhada" :
            Caminhada caminhada = new Caminhada();
 
            caminhada.setDuracao((long)(Integer.parseInt(jTextPane10.getText())));
            caminhada.setDistancia((double)(Integer.parseInt(jTextPane4.getText())));
            caminhada.setCondMeteo(jTextPane1.getText());
            caminhada.setLocal(jTextPane5.getText());
            caminhada.setData(jTextPane2.getText());
            caminhada.setAltitude((double)(Integer.parseInt(jTextPane8.getText())));
            
            this.fitnessUM.adicionaActividade(caminhada);
            
            case "Atletismo" :
             
            Atletismo atletismo = new Atletismo();
 
            atletismo.setDuracao((long)(Integer.parseInt(jTextPane10.getText())));
            atletismo.setDistancia((double)(Integer.parseInt(jTextPane4.getText())));
            atletismo.setCondMeteo(jTextPane1.getText());
            atletismo.setLocal(jTextPane5.getText());
            atletismo.setData(jTextPane2.getText());
            atletismo.setAltitude((double)(Integer.parseInt(jTextPane8.getText())));
            
            this.fitnessUM.adicionaActividade(atletismo);
            
                
            
            case "Futebol" :
            
            Futebol futebol = new Futebol();
 
            futebol.setDuracao((long)(Integer.parseInt(jTextPane10.getText())));
            futebol.setDistancia((double)(Integer.parseInt(jTextPane4.getText())));
            futebol.setCondMeteo(jTextPane1.getText());
            futebol.setLocal(jTextPane5.getText());
            futebol.setData(jTextPane2.getText());
            futebol.setGolos((Integer.parseInt(jTextPane6.getText())));
            
            this.fitnessUM.adicionaActividade(futebol); 
            
            case "Voleibol":
            Voleibol voleibol = new Voleibol();
 
            voleibol.setDuracao((long)(Integer.parseInt(jTextPane10.getText())));
            voleibol.setCondMeteo(jTextPane1.getText());
            voleibol.setLocal(jTextPane5.getText());
            voleibol.setData(jTextPane2.getText());
            voleibol.setPontos((Integer.parseInt(jTextPane3.getText())));
            
            this.fitnessUM.adicionaActividade(voleibol);
               
            
            case "Basquetebol":
            
            Basquetebol basquetebol = new Basquetebol();
 
            basquetebol.setDuracao((long)(Integer.parseInt(jTextPane10.getText())));
            basquetebol.setCondMeteo(jTextPane1.getText());
            basquetebol.setLocal(jTextPane5.getText());
            basquetebol.setData(jTextPane2.getText());
            basquetebol.setCestos((Integer.parseInt(jTextPane7.getText())));
            
            this.fitnessUM.adicionaActividade(basquetebol);   
                   
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane10;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane jTextPane6;
    private javax.swing.JTextPane jTextPane7;
    private javax.swing.JTextPane jTextPane8;
    // End of variables declaration//GEN-END:variables
}
